development:
  adapter: postgresql
  encoding: unicode
  database: icd10forum_development
  pool: 5
  username: admin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: icd10forum_test
  pool: 5
  username: admin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: icd10forum_production
  pool: 5
  username: admin
  password:

